version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-data}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
  application:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - .:/application
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend


networks:
  backend:
    driver: bridge
    name: backend


volumes:
    postgres:
